version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  server:
    #image: backend
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=sa
      - DB_PASSWORD=1234
      - DB_HOST=mysqldb
      - DB_NAME=employeedb
      #- spring.datasource.url=jdbc:mysql://$DB_HOST:3306/$DB_NAME?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      mysqldb:
        condition: service_healthy
    command: sh -c "/wait && /sayhello"

networks:
  springmysql-net: